config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_chelck
  #
  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  has_rich_text :content
  has_one_attached :cover_image

  scope :sorted,
        -> do
          order(arel_table[:published_at].desc.nulls_first).order(
            updated_at: :desc
          )
        end
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!
  before_action :set_blog_post
  #delete cover images by id

  def destroy
    @blog_post.cover_image.purge_later
    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post) }
      format.turbo_stream do
        render turbo_stream:
                 turbo_stream.remove(dom_id(@blog_post, :cover_image))
      end
    end
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_blog_post, except: %i[index new create]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
    @pagy, @blog_posts = pagy(@blog_posts)
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(
      :title,
      :content,
      :published_at,
      :cover_image
    )
  end

  def set_blog_post
    if user_signed_in?
      @blog_post = BlogPost.find(params[:id]) #find any post
    else
      @blog_post = BlogPost.published.find(params[:id]) # only published post
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form|%>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div>
    <%= form.label :title%>
    <%= form.text_field :title%>
  </div>
  <div>
    <%= form.label :cover_image %>
    <% if @blog_post.cover_image.present?  %>
      <div id="<%= dom_id(@blog_post, :cover_image) %>">
        <%= image_tag @blog_post.cover_image, class: 'w-1/3' if @blog_post.cover_image.present?  %>
        <%= link_to "Remove cover image", blog_post_cover_image_path(@blog_post), data: {turbo_method: :delete, turbo_confirm: "are you sure?"} %>
      </div>
    <% end %>
    <%= form.file_field :cover_image %>
  </div>
  <div>
    <%= form.label :content%>
    <%= form.rich_text_area :content%>
  </div>
  <div>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_blank: true %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>edit blog post</h1>
<%= render partial: "form", local: {blog_post: @blog_post}%>
<%= button_to "delete", @blog_post, method: :delete, data: {turbo_confirm: "are you sure?"} %>

app/views/blog_posts/index.html.erb
<h1 class="text-4xl font-bold">Blogs</h1>
<div class="block">
  <% @blog_posts.each do |post| %>
    <div class="mb-6">
      <%= image_tag post.cover_image if post.cover_image.present? %>
      <% if post.draft? %>
        <div class="text-gray-600 bg-gray-100 rounded inline-block px-2 py-1 text-xs">Draft</div>
      <% elsif post.scheduled?  %>
        <div class="text-gray-600 bg-gray-100 rounded inline-block px-2 py-1 text-xs">Draft</div>
      <% end %>
      <h2 class="mt-0"><%= link_to post.title, post, class: 'no-underline font-medium text-xl text-blue-600' %></h2>
      <p><%= post.content %></p>
    </div>
  <% end %>
  <%== pagy_nav(@pagy)%>
</div>

app/views/blog_posts/new.html.erb
<h1>New post</h1>
<%= render partial: "form", local: {blog_post: @blog_post}%>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in?  %>
<h1><%= @blog_post.title %></h1>
<%= image_tag @blog_post.cover_image if @blog_post.cover_image.present? %>
<p><%= @blog_post.content %></p>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="prose container mx-auto mt-28 px-5 flex gap-8 flex-col">
      <p class="notice absolute"><%= notice %></p>
      <p class="alert absolute"><%= alert %></p>
      <header>
        <% if user_signed_in? %>
          <%= link_to "New post", new_blog_post_path %>
          <%= button_to "logout", destroy_user_session_path, :method => :delete %>
        <% end %>
      </header>
      <%= yield %>
    </main>
  </body>
</html>